
// Code generated by gox; DO NOT EDIT.
package gox
import (
	"github.com/caleb-sideras/gox2/src/app/docs/routing/pages-and-index"
	"github.com/caleb-sideras/gox2/src/app/docs/routing/defining-routes"
	"github.com/caleb-sideras/gox2/src/app/projects/musicgpt"
	"github.com/caleb-sideras/gox2/src/app/docs/routing/hx-boost"
	"github.com/caleb-sideras/gox2/src/app/projects/caas/cluster"
	"github.com/caleb-sideras/gox2/src/app/examples/static-render"
	"github.com/caleb-sideras/gox2/src/app/examples/todo"
	"github.com/caleb-sideras/gox2/src/app/docs/projectStructure"
	"github.com/caleb-sideras/gox2/src/app/blog"
	"github.com/caleb-sideras/gox2/src/app/blog/temporarystandard"
	"github.com/caleb-sideras/gox2/src/app/docs/routing/dynamic-routes"
	"github.com/caleb-sideras/gox2/src/app/projects/goxFramework"
	"github.com/caleb-sideras/gox2/src/app/docs/routing"
	"github.com/caleb-sideras/gox2/src/app/examples/_slug_/dynamic-routes"
	"github.com/caleb-sideras/gox2/src/app"
	"github.com/caleb-sideras/gox2/src/app/experience"
	"github.com/caleb-sideras/gox2/src/app/_test_"
	"github.com/caleb-sideras/gox2/src/app/home_"
	"github.com/caleb-sideras/gox2/src/app/docs/index"
	"github.com/caleb-sideras/gox2/src/app/docs/routing/static-pages-and-routes"
	"github.com/caleb-sideras/gox2/src/app/docs/routing/suspense"
	"github.com/caleb-sideras/gox2/src/app/projects/peoplepedia"
	"github.com/caleb-sideras/gox2/src/app/docs/pages"
	"github.com/caleb-sideras/gox2/src/app/docs/routing/caching"
	"github.com/caleb-sideras/gox2/src/app/examples/suspense"
	"github.com/caleb-sideras/gox2/src/app/projects/caas/segmentation"
	"github.com/caleb-sideras/gox2/src/app/projects"
	"github.com/caleb-sideras/gox2/src/app/projects/tweetailyze"
	"github.com/caleb-sideras/gox2/src/app/docs/index/templ"
	"github.com/caleb-sideras/gox2/src/app/projects/caas/processor"
	"github.com/caleb-sideras/gox2/src/app/docs/introduction_"
	"github.com/caleb-sideras/gox2/src/app/docs/pages/static-pages"
	"github.com/caleb-sideras/gox2/src/app/docs/pages/templ"
	"github.com/caleb-sideras/gox2/src/app/_test_/rn"
	"github.com/caleb-sideras/gox2/src/app/projects/caas"
)

var IndexList = map[string]IndexDefaultFunc{
	"/projects" : app.Index,
	"/docs/routing/dynamic-routes" : app.Index,
	"/docs/pages" : app.Index,
	"/projects/caas/processor" : app.Index,
	"/examples/{slug}" : app.Index,
	"/{test}" : app.Index,
	"/examples/todo" : app.Index,
	"/projects/tweetailyze" : app.Index,
	"/examples/suspense" : app.Index,
	"/docs/project-structure" : app.Index,
	"/" : app.Index,
	"/docs/routing/static-pages-and-routes" : app.Index,
	"/examples/{slug}/dynamic-routes" : app.Index,
	"/docs" : app.Index,
	"/examples/static-render" : app.Index,
	"/docs/index" : app.Index,
	"/docs/routing/hx-boost" : app.Index,
	"/docs/index/templ" : app.Index,
	"/projects/caas" : app.Index,
	"/examples" : app.Index,
	"/docs/routing/defining-routes" : app.Index,
	"/projects/caas/segmentation" : app.Index,
	"/blog" : app.Index,
	"/blog/temporarystandard" : app.Index,
	"/docs/routing/suspense" : app.Index,
	"/projects/peoplepedia" : app.Index,
	"/projects/gox-framework" : app.Index,
	"/docs/routing/caching" : app.Index,
	"/docs/pages/static-pages" : app.Index,
	"/projects/musicgpt" : app.Index,
	"/{test}/rn" : app.Index,
	"/docs/routing/pages-and-index" : app.Index,
	"/experience" : app.Index,
	"/docs/routing" : app.Index,
	"/docs/pages/templ" : app.Index,
	"/projects/caas/cluster" : app.Index,
}

var PageRenderList = []RenderDefault{
	{"/experience", experience.Page_},
	{"/blog", blog.Page_},
}

var RouteRenderList = []RenderDefault{
	{"/{test}/example", test.Example_},
}

var PageHandleList = []Handler{
	{"/docs/routing/pages-and-index", docs_routing_pagesandindex.Page, DefaultHandler},
	{"/projects/caas/processor", caas_processor.Page, ResReqHandler},
	{"/docs/routing/caching", docs_routing_caching.Page, DefaultHandler},
	{"/examples/suspense", examples_suspense.Page, ResReqHandler},
	{"/docs", docs_introduction.Page, DefaultHandler},
	{"/docs/project-structure", docs_projectstructure.Page, DefaultHandler},
	{"/docs/pages/static-pages", docs_pages_staticpages.Page, DefaultHandler},
	{"/docs/pages/templ", docs_pages_templ.Page, DefaultHandler},
	{"/projects/caas/cluster", caas_cluster.Page, ResReqHandler},
	{"/projects/caas/segmentation", caas_segmentation.Page, ResReqHandler},
	{"/docs/routing/defining-routes", docs_routingfundamentals.Page, DefaultHandler},
	{"/examples/static-render", examples_staticrender.Page, DefaultHandler},
	{"/", home.Page, ResReqHandler},
	{"/projects", projects.Page, ResReqHandler},
	{"/blog/temporarystandard", temporarystandard.Page, ResReqHandler},
	{"/docs/index", docs_index.Page, DefaultHandler},
	{"/docs/routing/static-pages-and-routes", docs_routing_staticpagesandroutes.Page, DefaultHandler},
	{"/docs/routing/suspense", docs_routing_suspense.Page, DefaultHandler},
	{"/projects/musicgpt", musicgpt.Page, ResReqHandler},
	{"/projects/peoplepedia", peoplepedia.Page, ResReqHandler},
	{"/docs/routing/dynamic-routes", docs_routing_dynamicrouting.Page, DefaultHandler},
	{"/docs/routing/hx-boost", docs_routing_hxboost.Page, DefaultHandler},
	{"/{test}/rn", rn.Page, DefaultHandler},
	{"/docs/pages", docs_pages.Page, DefaultHandler},
	{"/examples/todo", examples_todo.Page, ResReqHandler},
	{"/projects/gox-framework", gox.Page, ResReqHandler},
	{"/projects/tweetailyze", tweetailyze.Page, ResReqHandler},
	{"/docs/index/templ", docs_index_templ.Page, DefaultHandler},
	{"/docs/routing", docs_routing.Page, DefaultHandler},
	{"/examples/{slug}/dynamic-routes", examples_dynamicroutes.Page, ResReqHandler},
	{"/projects/caas", caas.Page, ResReqHandler},
}

var RouteHandleList = []Handler{
	{"/examples/suspense/example", examples_suspense.Example, DefaultHandler},
	{"/examples/suspense/code", examples_suspense.Code, DefaultHandler},
	{"/{test}/example2", test.Example2, DefaultHandler},
	{"/examples/static-render/example", examples_staticrender.Example, DefaultHandler},
	{"/examples/static-render/code", examples_staticrender.Code, DefaultHandler},
	{"/projects/musicgpt/readme", musicgpt.Readme, DefaultHandler},
	{"/projects/musicgpt/videos", musicgpt.Videos, DefaultHandler},
	{"/examples/todo/example", examples_todo.Example, DefaultHandler},
	{"/examples/todo/addtask", examples_todo.AddTask, ResReqHandler},
	{"/examples/todo/code", examples_todo.Code, DefaultHandler},
	{"/projects/gox-framework/videos", gox.Videos, DefaultHandler},
	{"/projects/gox-framework/readme", gox.Readme, DefaultHandler},
	{"/examples/{slug}/dynamic-routes/example", examples_dynamicroutes.Example, ResReqHandler},
	{"/examples/{slug}/dynamic-routes/code", examples_dynamicroutes.Code, DefaultHandler},
	{"/projects/caas/readme", caas.Readme, DefaultHandler},
	{"/projects/caas/videos", caas.Videos, DefaultHandler},
}
